import type { Metadata } from "next";

import "./globals.css";
import Header from "@/layout/header/Header";


export const metadata: Metadata = {
  title: "Guilherme Barroso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
      </body>
    </html>
  );
}
