import type { Metadata } from "next";

import "./globals.css";
import Header from "@/layout/header/Header";
import LoadingScreen from "@/components/loading/LoadingScreen";

export const metadata: Metadata = {
  title: "Guilherme | Criação de Sites Profissionais",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`h-full antialiased`}
    >
      <body className="relative min-h-full flex flex-col">
        <LoadingScreen/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
